services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: image-gallery-api-prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DEBUG=False
      - UNSPLASH_KEY=${UNSPLASH_KEY:-}
    env_file:
      - ./api/.env.local
    restart: unless-stopped
    networks:
      - image-gallery-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: image-gallery-frontend-prod
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - image-gallery-network

networks:
  image-gallery-network:
    driver: bridge
