services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: image-gallery-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=True
    env_file:
      - ./api/.env.local
    volumes:
      - ./api:/app
      - /app/.venv
    restart: unless-stopped
    networks:
      - image-gallery-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: image-gallery-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - image-gallery-network

networks:
  image-gallery-network:
    driver: bridge
