services:
  api:
    restart: always
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: image-gallery-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=True
    env_file:
      - ./api/.env.local
    volumes:
      - ./api:/app
      - /app/.venv
    networks:
      - image-gallery-network

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: image-gallery-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAI_USEPOLLING=true      
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - image-gallery-network

  mongo:
    image: mongo:6.0
    container_name: image-gallery-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo_data:/data/db
    networks:
      - image-gallery-network

  mongo-express:
    image: mongo-express:1.0.0-20
    container_name: image-gallery-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    networks:
      - image-gallery-network

volumes:
  mongo_data:
    driver: local

networks:
  image-gallery-network:
    driver: bridge
